### ISSUE TITLE
Ability Patch can not be used on Articuno

### ISSUE THREAD

**Issue by DZtheCasual** [Cobblemon-Islands/Bugs-And-Issues#47] opened 2023-12-14 00:08 UTC
Feature: Ability Patch

Expected Behaviour: Change Articuno's Ability to its hidden ability

Current Behaviour: Says ability patch can not be used on this pokemon

Video Recordings/Screenshots: 
![2023-12-13_18 06 44](https://github.com/Cobblemon-Islands/Bugs-And-Issues/assets/150404624/46545eed-d53b-476c-8f88-979cb11ad705)

How to reproduce the bug: Try using an ability patch on an Articuno

**Comment by Adainish** [comment] 2023-12-14 23:40
This is as intended, Legendaries shouldn't be capable of being edited through ability items.

**Comment by Adainish** [comment] 2023-12-14 23:40
Closing

**Closed as not planned by Adainish** 2023-12-14 23:40 UTC
Labels: wontfix
